### ISSUE TITLE
The Apple Lightning Digital AV Adapter don't work after jb (10.2) with Yalu102

### ISSUE THREAD

**Issue by q118118** [kpwn/yalu102#204] opened 2017-01-29 14:10 UTC
The issue is that the adapter cannot be detected. My iPhone SE and iPhone 6s+ (Samsung) are having the same problem. Both devices are on 10.2.

The adapter will work again after reboot and without jb. I also tried to jb will the adapter attached but the result is still the same.

Any log files / any further info can help? Thanks.

**Comment by joshmedia2016** [comment] 2017-01-29 14:38
its an issue with your adpter  not anything else
thanks Jailbreak team

**Comment by keldegar** [comment] 2017-01-29 17:17
I'm also having this issue with apple HDMI adapter. It says this accessory is not supported.

**Comment by dareal68** [comment] 2017-01-29 19:25
I confirm this issue, adapter is working in "normal mode" and stop working when jailbroken.

**Comment by eriksmets** [comment] 2017-01-30 06:48
I don't have this adapter. Could someone test if running 'killall mediaserverd' over SSH before attaching the adapter works ?

**Comment by dareal68** [comment] 2017-01-30 11:31
I just tried 'killall mediaserverd' over SSH and after I attach my adapter to my phone, it didn't help at all. I hope someone will find a fix.

Thanks.

**Comment by ReddestDream** [comment] 2017-01-30 14:01
Can confirm this issue. I don't get "Accessory not Supported" but the title bar never turns blue, it's like it's never even detected at all. :/

I can confirm I get video out after reboot before re-jailbreak but not after jailbreak with the same setup.

**Comment by GibFTW** [comment] 2017-01-31 01:37
Is this error still occuring in the new build out of curiosity?

**Comment by ReddestDream** [comment] 2017-01-31 01:50
It's still broken on beta 7. I'm a bit leery to try building anymore myself since the 10.2 signing has closed. I can check again on the next beta.

**Comment by MihDyachkov** [comment] 2017-01-31 09:17
I confirm this issue on iPad mini 2. After reboot all works perfectly.

**Comment by dareal68** [comment] 2017-01-31 20:42
I compile latest commit (aka beta 7) and the issue is still occurring.

**Comment by eriksmets** [comment] 2017-01-31 20:43
I was able to confirm with @ReddestDream today that the issue is caused by the reloading of userland.

**Comment by dareal68** [comment] 2017-01-31 20:46
@eriksmet do you have any suggestion?

**Comment by ReddestDream** [comment] 2017-01-31 21:56
From our last trial, it doesn't seem to be the accessory daemons. We tried omitting the accessory daemons from being reloaded, and the issue still occurred after reloading userland.

**Comment by ReddestDream** [comment] 2017-02-01 04:15
What's also interesting is that USB drives and USB ethernet still work fine. It only seems to be video adapters that are affected by this . . .

**Comment by meljigson** [comment] 2017-02-01 09:27
I am also having this issue with my 6s. Seeking solution.

**Comment by ReddestDream** [comment] 2017-02-02 18:59
See.

https://github.com/kpwn/yalu102/pull/378/commits

**Comment by tactrevor** [comment] 2017-02-02 20:29
Same issue on iPhone 5s running iOS 10.1.1 jailbreak. PLEASE HELP,  I have been rebooting to unjailbreak in order to use it than rejailbreaking after it is terrible
To not be able to use tweaks on video apps though.

**Comment by NotAlexNoyle** [comment] 2017-02-02 20:33
@tactrevor have you tried the latest update? Just submitted 2 hours ago - you will need to compile yourself.

**Comment by kpwn** [comment] 2017-02-02 21:13
Last commit fixes this- closing, but still looking for a better solution.

**Closed by kpwn** 2017-02-02 21:13 UTC
