### ISSUE TITLE
AirPods updates not working

### ISSUE THREAD

**Issue by rohidjetha** [kpwn/yalu102#376] opened 2017-02-02 17:44 UTC
Airpods updates not working. I think it's because Yalu is blocking iOS updates. Not sure.

Here's the thread on Reddit: https://reddit.com/r/jailbreak/comments/5rnyen/question_someone_succeed_to_update_airpods/

**Comment by rohidjetha** [comment] 2017-02-02 17:46
EDIT: it's working on non jailbroken mode. Sorry about the issue.

**Comment by OGKevin** [comment] 2017-02-02 19:06
if this is solved can u please close the issue

**Comment by Aaahh** [comment] 2017-02-02 19:52
The issue isn't solved, he just found a work around

**Comment by ReddestDream** [comment] 2017-02-02 21:33
I don't have airpods, so I don't know for sure, but maybe it's also resolved by the HDMI fix that was just merged. The fud daemon that was excluded is used to update accessory firmwares. Maybe it affects this too? Try recompiling from source or changing the reload script.

**Closed** 2017-02-03 17:14 UTC
