### ISSUE TITLE
iMessage gifs don't work

### ISSUE THREAD

**Issue by Macros2003** [kpwn/yalu102#337] opened 2017-01-31 14:42 UTC
After jail breaking with the latest beta 7 the iMessage gifs don't work if I reboot they work but when I rejailbreak the don't work.Please help

**Comment by Aaahh** [comment] 2017-01-31 14:55
https://github.com/kpwn/yalu102/issues/294

**Comment by atkr** [comment] 2017-01-31 14:56
This is a duplicate of #294

**Closed** 2017-01-31 15:38 UTC
