### ISSUE TITLE
iPad Air 2 / IPad Mini 4 success rate much higher thanks to this method

### ISSUE THREAD

**Issue by MEXX1811** [kpwn/yalu102#435] opened 2017-02-13 22:48 UTC
If you run YALU102 **First** then exit but leave it running and open about **6 random apps** then go back into Yalu and wait about **5 - 10 seconds** and press go you should be able to get jail broken again, I have jailbroken my iPad Air 2 twice on first and second try, iPad mini 4 people have told me this works but **please confirm** 

Before doing this I couldn't get jailbroken again but after doing this it's worked. (iPad Air 2)

**if your device reboots upon pressing 'go' or 'fails' please manually turn off your device by 'sliding to power off' **close all apps before turning off device** then turning back on and retrying the steps.

**please let me know if this works for you guys 🙂 Hope it helps**

**Comment by KashubaK** [comment] 2017-02-14 04:12
iP6 on iOS 10.1 reporting in, not working after a few tries. Will keep trying and will post again if there is success.

**Comment by MEXX1811** [comment] 2017-02-14 10:41
Oh, for me I've jail broken my iPad Air 2 a few times now, whereas before it wouldn't do it, it was almost impossible but after doing this it works

**Comment by haze4** [comment] 2017-02-14 14:55
This helps the success rate of rejailbreaking but still get random reboots

**Comment by MEXX1811** [comment] 2017-02-14 15:24
@haze4 yes but at least we can get into jailbreak again

**Comment by nullpixel** [comment] 2017-02-14 17:04
Dupe of #424

**Comment by MEXX1811** [comment] 2017-02-14 17:12
@nullpixel1 sorry just letting people know about this method so they can get jail broken again

**Closed as completed** 2017-02-16 03:45 UTC
