### ISSUE TITLE
PROBLEM CYDIA error

### ISSUE THREAD

**Issue by ardit12345** [kpwn/yalu102#334] opened 2017-01-31 12:31 UTC
i cant update cydia in 64 bit 
error HHTP/1.1 503 Service Unavailable
can i fix this?
ples help

**Comment by Mila432** [comment] 2017-01-31 12:49
https://github.com/kpwn/yalu102/issues/64

**Comment by tjsreece** [comment] 2017-01-31 12:57
We can't help you since your problem is not related. Please close this issue @ardit12345

**Comment by eXhumer1149** [comment] 2017-01-31 14:01
Use issue only for Yalu Code related issues. Use r/jailbreak for help with Cydia.

#162

**Comment by DarknesGaming** [comment] 2017-01-31 16:44
@Mila432 you referenced the "stop asking for support" issue. This isn't asking for support.
@ardit12345 close this issue before @kpwn does. This is not an issue that's on our end.
Little bit of a comment about Cydia: HTTP/1.1?! That's a really old protocol! Why would Cydia use that?

**Comment by OGKevin** [comment] 2017-01-31 16:54
This is not a support forum or generic mailing list.

This form is exclusively for reporting issues caused directly by the inner workings of yalu.

Direct your jailbreaking questions to one of these fine communities:

- https://reddit.com/r/jailbreak
- http://www.jailbreakqa.com/

Issues, which are not related to yalu's code, may be closed without comment. Do NOT post about: Cydia, tweak, respring/bootloop or app issues UNLESS you have evidence that they are caused by an error in the jailbreaking software itself.

(Delete this bit after reading, and replace it by "I read the issue posting guidelines.") #162

**Closed** 2017-01-31 17:31 UTC
